[package]
name = "relative-import"
version = "0.1.0"
authors = ["Wadii Hajji <wadii.hajji@etu.univ-amu.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
